- name: apply configuration to dbservers
  hosts: dbservers
  user: deploy
  sudo: yes
  vars:
    postgresql_databases:
     - name: uniformity

    postgresql_users:
     - name: uniformity
       pass: uniformity

    postgresql_user_privileges:
     - name: uniformity
       db: uniformity
       priv: "ALL"

  roles:
    - Ansibles.postgresql
