- name: apply configuration to webservers
  hosts: webservers
  user: deploy
  sudo: yes
  vars:
    nginx_user: "www-data"
    nginx_sites:
      uniformity:
        - listen 80
        - server_name uniformity.com
        - index index.php index.html
        - location / { try_files $uri @yourapplication; }
        - location @yourapplication {
            include uwsgi_params;
            uwsgi_pass unix:/tmp/uwsgi_uniformity.sock;
           }

        - location /static {
            alias /home/chase/uniformity/app/static;
            gzip on;
          }

  roles:
    - jdauphant.nginx
    - uniformity
